on:
  push:
    branches: [ main ]

jobs:
  build-test-app:
    runs-on: ubuntu-latest
    steps:
        - name: checkout code
          uses: actions/checkout@v3
        - name: setup docker build
          uses: docker/setup-buildx-action@v2
        - name: build docker image
          run: docker build -t fastapi-app .
        - name: run test inside container
          run: docker run --rm fastapi-app pytest -v
        - name: scan with sbom using syft
          uses: anchore/sbom-action@v0
          with:
            image: fastapi-app:latest
            format: spdx-json
            output-file: sbom.json



